package au.com.api.wallet.dao.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import au.com.api.wallet.dao.entity.core.IdentityEntity;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.FieldNameConstants;

@Entity
@Table(name = "payment_transaction")
@Getter
@Setter
@FieldNameConstants
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class PaymentTransactionEntity extends IdentityEntity {

    /**
     * The unique immutable transaction id generated by the client to uniquely identify the resource. It is to be used by
     * clients to retrieve an instance of the resource.
     */
    @Column(name = "transaction_id", unique = true, nullable = false)
    protected UUID transactionId;

    @Column(name = "user_name")
    protected String userName;

    @Column(name = "amount")
    protected long amount;

    @Column(name = "type")
    protected String type;

    @Column(name = "type_method")
    protected String typeMethod;

    @Column(name = "state")
    protected String state;

    @Column(name = "description")
    protected String description;

    @Column(name = "currency")
    protected String currency;

    @Column(name = "created_at")
    protected LocalDateTime createdAt;

    @Column(name = "updated_at")
    protected LocalDateTime updatedAt;

    @Column(name = "debit_credit")
    protected String debitCredit;

    @ManyToOne
    @JoinColumn(name = "user_id")
    protected AccountEntity account;

    @Builder(toBuilder = true)
    public PaymentTransactionEntity(
            final UUID id,
            final String userName,
            final LocalDateTime createdAt,
            final LocalDateTime updatedAt,
            final long amount,
            final String type,
            final String typeMethod,
            final String state,
            final String description,
            final String currency,
            final String debitCredit,
            final UUID transactionId,
            final AccountEntity account) {

        super(id);

        this.userName = userName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.amount = amount;
        this.type = type;
        this.typeMethod = typeMethod;
        this.state = state;
        this.description = description;
        this.currency = currency;
        this.debitCredit = debitCredit;
        this.transactionId = transactionId;
        this.account = account;
    }

    public static class PaymentTransactionEntityBuilder extends IdentityEntityBuilder {
    }

}
